title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: media
            field:
              max_files: 1
              container: assets
              type: assets
              display: Media
              folder: projects
              validate:
                - required
              width: 66
          -
            handle: disable_media_scroll
            field:
              type: toggle
              display: 'Disable Media Scroll'
              width: 33
          -
            handle: technologies
            field:
              type: text
              display: Technologies
              validate:
                - required
          -
            handle: live_link
            field:
              type: link
              display: 'Live Link'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - projects
              max_items: 1
              listable: false
              localizable: true
